# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

# npm install 
- task: UseNode@1
  inputs:
    checkLatest: true
 
# npm install 
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'Passingwind.Blog.Web/ClientApp'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    modifyOutputPath: false
    
# .net core build.
#- script: dotnet build --configuration $(buildConfiguration)
#  displayName: 'dotnet build $(buildConfiguration)'

# github release / tag
- task: GitHubRelease@1
  displayName: 'GitHub release'
  inputs:
    gitHubConnection: 'github.com_jxnkwlp'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: 'v$(Build.BuildNumber)'
    title: 'v$(Build.BuildNumber)'
    isDraft: true
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'
